package pojos;
// Generated 2022.01.02. 10:22:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Konyv generated by hbm2java
 */
@Entity
@Table(name="konyv"
    ,catalog="konyvtaras"
)
public class Konyv  implements java.io.Serializable {


     private Integer id;
     private Tag tag;
     private String szerzo;
     private String cim;
     private int oldalszam;

    public Konyv() {
    }

    public Konyv(Tag tag, String szerzo, String cim, int oldalszam) {
       this.tag = tag;
       this.szerzo = szerzo;
       this.cim = cim;
       this.oldalszam = oldalszam;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="tag_id", nullable=false)
    public Tag getTag() {
        return this.tag;
    }
    
    public void setTag(Tag tag) {
        this.tag = tag;
    }

    
    @Column(name="szerzo", nullable=false, length=65)
    public String getSzerzo() {
        return this.szerzo;
    }
    
    public void setSzerzo(String szerzo) {
        this.szerzo = szerzo;
    }

    
    @Column(name="cim", nullable=false, length=65)
    public String getCim() {
        return this.cim;
    }
    
    public void setCim(String cim) {
        this.cim = cim;
    }

    
    @Column(name="oldalszam", nullable=false)
    public int getOldalszam() {
        return this.oldalszam;
    }
    
    public void setOldalszam(int oldalszam) {
        this.oldalszam = oldalszam;
    }




}


